### ISSUE TITLE
Ability to list people.

### ISSUE THREAD

**Issue by lcpriest** [delighted/delighted-ruby#18]
Would be great to be able to fetch persons from the API as there is currently no way to associate a response to a person via the API. (unless the person was created from my own app and I retained a reference)

**Comment by mkdynamic** [comment]
@lcpriest This sounds like a good idea. Would you want to lookup people by email?

As a workaround, it might be possible to do what you need with the `/v1/people` endpoint, which allows you create and update people by email. For example:

```ruby
person = Delighted::Person.create(email: "existing@email.com", name: "James Scott", send: false)
person.id # will return the ID of the existing person

person = Delighted::Person.create(email: "new@email.com", name: "Janet Smith", send: false)
person.id # will return the ID of the newly created person
```

The key is `send: false` so that endpoint just acts as a means to create and update people.

It's not ideal, but perhaps that might help you out until we add a proper way to lookup people via the API. Let me know if you have any other thoughts or questions. Thanks again for your suggestion.

**Comment by lcpriest** [comment]
I'd love to look them up by `external_id`, i.e. I keep a reference of the id from delighted in my system - email would work though.

Ultimately I want to be able to keep a CRM in sync with data from Delighted, but at the moment I can't pull anything from Delighted at all, though with your workaround I can validate that a contact is in the Delighted system, but the lookup is o(n), as opposed to being able to page through 100 or 250 at a time.

**Comment by mkdynamic** [comment]
Gotcha. So to verify I understand what would be an ideal solution for this:

- You hit an endpoint with a batch of Delighted Person IDs (which you saved when creating the people in Delighted)
- We return all the responses for those people

Sound right?

The `person_id` and `person_email` filters on the `/v1/survey_responses` endpoint do this, but only for single IDs/emails.

Also, what CRM are you using? We are continually adding more integrations to sync data between Delighted and external systems.

**Comment by lcpriest** [comment]
Ah, almost.

Yes, it would be useful if I could hit an endpoint and receive the data about all of the responses, filtered by person id.

But I also would like the ability to hit an endpoint and get all contacts in Delighted as well, so I can associate them with Zendesk, Intercom and Salesforce contacts in our system and merge the data from all of the systems.

Ah, I think I wasn't clear enough. I was referring to the CRM functionality in our own product, our customers are also Delighted customers and I wanted to be able to link the two systems.

**Comment by mkdynamic** [comment]
Gotcha, thanks for the clarification.

**Comment by lcpriest** [comment]
Thanks for the tip on the first comment, I have a good working syncer.

**Comment by lcpriest** [comment]
The webhook system sorta/kinda provides what I need as it actually sends the customer name and email across when a customer submits a survey response.

I chose not to create a contact to check if they exist for every contact in our system as each account has around 40k contacts, it would still be much easier if there were an endpoint to fetch contacts, similar to what Promoter.io does `http://docs.promoter.apiary.io/#reference/contacts/get-all-contacts/get-all-contact-lists`

**Comment by mkdynamic** [comment]
@lcpriest Glad to hear that webhooks helped. An endpoint for listing people is on our roadmap, and understanding your use case is really helpful for us designing that. Will leave this ticket open. In the meantime, if you have other feedback on how this endpoint should work, please do let us know. Thanks again for the feedback.

**Comment by lcpriest** [comment]
Given that the contact model in Delighted only has email and name fields, filtering by name, email, created_at and updated_at would be perfect! 

Assuming it is paginated, a meta blob with total number of records would be wonderful also.

**Comment by lcpriest** [comment]
For others -> a minor workaround can be to use the expand parameter on the survey_responses.

`Delighted::SurveyResponse.all({ expand: ['person', 'notes'], since: @date }, client)`

This pulls contacts that have responded to surveys, though you still have the issue of possibly sending to a contact more often than desired if they are non-responsive.
