### ISSUE TITLE
Multiple accounts within same app?

### ISSUE THREAD

**Issue by tastycakeman** [delighted/delighted-ruby#21]
Didn't see this covered in the docs, but this gem doesn't support having multiple accounts and API_keys?

**Comment by mkdynamic** [comment]
@tastycakeman You need to manually create the `Delighted::Client` instances (one for each API key). And then you have to pass the client object as the last argument in any of the resource calls. There is an example at the bottom the README, under "Advanced configuration":
https://github.com/delighted/delighted-ruby#-advanced-configuration--testing

Assuming you're using Rails, you could setup the clients in a `config/initializers/delighted.rb`, something along the lines of:

```ruby
require "delighted"

module Delighted
  class << self
    attr_acessor :client_1, :client_2, ...
  end
end

Delighted.client_1 = Delighted::Client.new(api_key: "API_KEY_1")
Delighted.client_2 = Delighted::Client.new(api_key: "API_KEY_2")
...
```

Then in your code where you are making resource calls:

```ruby
# Add a person to the account identified by the API key in Delighted.client_1
Delighted::Person.create({ email: "foo@bar.com" }, Delighted.client_1)

# Get metrics for account identified by the API key in Delighted.client_2
Delighted::Metrics.retrieve({}, Delighted.client_2)
``

Hope that helps, let me know if that works for your scenario.

**Comment by tastycakeman** [comment]
Ah thanks! For some reasons didn't see that, closing this issue.

**Comment by mkdynamic** [comment]
@tastycakeman No problem!
